/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusRegistrar -p dbus_registrar com.canonical.AppMenu.Registrar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus_registrar.h"

/*
 * Implementation of interface class DBusRegistrar
 */


QDBusArgument &operator<<(QDBusArgument &argument, const MenuStruct &menuStruct)
{
    argument.beginStructure();
    argument << menuStruct.wId << menuStruct.service << menuStruct.path;
    argument.endStructure();
    return argument;
}
const QDBusArgument &operator>>(const QDBusArgument &argument, MenuStruct &menuStruct)
{
    argument.beginStructure();
    argument >> menuStruct.wId >> menuStruct.service >> menuStruct.path;
    argument.endStructure();
    return argument;
}
QDebug operator<<(QDebug deg, const MenuStruct &menuStruct)
{
    qDebug() << "wId:" << menuStruct.wId << "server:" << menuStruct.service << "path:" << menuStruct.path;

    return deg;
}

DBusRegistrar::DBusRegistrar(QObject *parent)
    : QDBusAbstractInterface(staticServiceName(), staticPathName(), staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
    // qRegisterMetaType<MenuStruct>("MenuStruct");
    qDBusRegisterMetaType<MenuStruct>();
    qDBusRegisterMetaType<MenuList>();
}

DBusRegistrar::~DBusRegistrar()
{
}

