/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c RegistrarProxy -p registrar_proxy org.valapanel.AppMenu.Registrar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "registrar_proxy.h"

/*
 * Implementation of interface class RegistrarProxy
 */

RegistrarProxy::RegistrarProxy(QObject *parent)
    : QDBusAbstractInterface(staticServiceName(), staticPathName(), staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
}

RegistrarProxy::~RegistrarProxy()
{
}

