Document: me.imever.dde-top-panel
Title: Debian me.imever.dde-top-panel Manual
Author: <insert document author here>
Abstract: This manual describes what me.imever.dde-top-panel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/me.imever.dde-top-panel/me.imever.dde-top-panel.sgml.gz

Format: postscript
Files: /usr/share/doc/me.imever.dde-top-panel/me.imever.dde-top-panel.ps.gz

Format: text
Files: /usr/share/doc/me.imever.dde-top-panel/me.imever.dde-top-panel.text.gz

Format: HTML
Index: /usr/share/doc/me.imever.dde-top-panel/html/index.html
Files: /usr/share/doc/me.imever.dde-top-panel/html/*.html
